version: '3'
services:
  movies:
    image: sohailali31/movies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: sohailali31/train:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image: sohailali31/dth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  recharge:
    image: sohailali31/recharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
